### ISSUE TITLE
Inconsistent OpenAPI Specification

### ISSUE THREAD

**Issue by FrankLindert** [e-Spirit/fcecom-fsm#2]
We found two issues with the documentation:

- the X-total Header is also necessary for the "/categories/tree" route because the function BridgeRequest.getItems() is used in EcomBridgeAPI.getCategoriesTree(). 
- the calls to get the categories, products or content pages use trailing slashes (e.g. "/categories/"), in the openAPI it ist defined with "/categories". In frameworks like next.js this is a big difference.

**Comment by heiland-es** [comment]
We addressed this issue in the openApi.yaml with the last release: https://docs.e-spirit.com/ecom/fsconnect-com/FirstSpirit_Connect_for_Commerce_Releasenotes_EN.html#version-24-11-0
Issue: FCECOM-959

Bridge API doc & yaml can be found here: https://docs.e-spirit.com/ecom/fsconnect-com-api/FirstSpirit_Connect_for_Commerce_Bridge_API_EN.html
